version: 2

before:
  hooks:
    - go mod tidy

builds:
  - binary: pulse
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- .Arch }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: moonlight8978
    name: pulse

  footer: >-

    ---

    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
